### ISSUE TITLE
Direct payment from eclair to lnd fails with FinalIncorrectCltvExpiry

### ISSUE THREAD

**Issue by cdecker** [cdecker/lightning-integration#3]
After resolving #2 we are unable to route a direct payment. Apparently this is due to a disagreement on what the final CLTV should be:

```
DEBUG:root:eclair: 2017-09-22 13:34:12,034 WARN  f.a.eclair.payment.PaymentLifecycle akka://default/user/$h/payment-initiator/$a  - received an error message from target nodeId=026ea05e2cc68d186f46e238a623361f99713346e5b6cf16a12b53de4900ab8f92, failing the payment (failure=FinalIncorrectCltvExpiry(2487))
```

This is the test_direct_payment test, with eclair opening a channel to lnd and initiating a single transfer. Full logs can be found on [gist](https://gist.github.com/anonymous/7d7ee2e5802ff7fe9d1767dfa9444cc0)

**Comment by cdecker** [comment]
Ping @Roasbeef and @sstone

**Comment by sstone** [comment]
we send a htlc with an expiry of 2487 and a final expiry of 2487 which should be correct since it is a direct payment so `cltv_expiry_delta` should be 0 

@cdecker does the same test work between lightningd and lnd ?

**Comment by cdecker** [comment]
Nope, we also get an incorrect CLTV error ([logs](https://gist.github.com/anonymous/76abd2ce429db5d609cce9c3feb9e928)):

```
DEBUG:root:lnd: 2017-09-22 19:28:30.371 [ERR] HSWC: Onion payload of incoming htlc(d0d7f2f9aa60b865b605e174eea9c7559471c3ab5093caaf54ad928680a92570) has incorrect time-lock: expected 587, got 449
```

But this seems to be due to ElementsProject/lightning#281, namely it is using a timelock of 6 (c-lightning default) instead of 144 as required by `lnd`.

**Comment by cdecker** [comment]
Retesting just to get a full picture of where we stand with this test, an interesting pattern emerges:
```
test.py::test_direct_payment[eclair_eclair] PASSED
test.py::test_direct_payment[eclair_lightning] PASSED
test.py::test_direct_payment[eclair_lnd] FAILED
test.py::test_direct_payment[lightning_eclair] PASSED
test.py::test_direct_payment[lightning_lightning] PASSED
test.py::test_direct_payment[lightning_lnd] FAILED
test.py::test_direct_payment[lnd_eclair] FAILED
test.py::test_direct_payment[lnd_lightning] FAILED
test.py::test_direct_payment[lnd_lnd] FAILED
```

**Comment by Roasbeef** [comment]
If the height as `2487` (guessing that it was?), then sending an HTLC of `2487` is incorrect as it doesn't give the receiver sufficient time to actually pull the payment itself (a race condition as the sender can then immediately go to the second-level).  When a node advertises an expiry delta, that value should be observed _even_ if it's a regular single-hop payment. Otherwise, the "correct" CTLV expiry on the HTLC would be ambiguous. 

When testing with cdecker in SF a few weeks ago, we encountered this same issue and concluded that `lnd`'s behavior was correct. `lnd` has a related error w.r.t expecting the incorrect value in the onion payload itself, but that has been resolved now.

**Comment by cdecker** [comment]
According to the log `lnd` appears to be at height 2478, and repeating the run a couple of times `eclair` always adds a CLTV timeout of 9 (which I'm unsure where it comes from tbh).

```
DEBUG:root:lnd: 2017-09-22 13:34:11.617 [INF] CRTR: Block 249868fca78965b8c9f5c06afa448beb211538cd8db1c64aeae55f375101fa5b (height=2478) closed 0 channels
```

**Comment by sstone** [comment]
@Roasbeef this is not how I read the specs ("If there is no next hop, cltv_expiry_delta is zero") ?
@cdecker we currently set a default expiry of now + 9 blocks when the user does not specify one (we haven't yet implemented the fuzzing recommendations)

**Comment by cdecker** [comment]
Am I correct in assuming that `lnd` is expecting the next CLTV delta on the final to be the announced delta? Also doesn't the fixed delta of 9 leak that this is the last hop to the penultimate hop?

**Comment by Roasbeef** [comment]
@sstone that's for the payload itself, meaning the value in the payload should exactly be the value within the HTLC itself. If one sets the CLTV expiry to exactly the current height, then a race condition is introduced. When sending a payment across a link, the routing policy of the target link should be used, not yours. This is due to the fact that you're "transiting" their link essentially. 

@cdecker it expects the CLTV expiry to be `height_now + delta` as nodes advertise the amount of time they need to ensure they can disclose the pre-image in a timely manner. The fixed delta does leak, but as you've suggested in the pass, a "shadow route" can be used to ensure that delta isn't continually fixed. In this case, nodes would have some max delta parameter that they'd use as polict in order to avoid accepting/extending an HTLC with like a 300 day delta (as they should accept a value > than exactly what they expect).

**Comment by cdecker** [comment]
I can confirm that if I set c-lightning to the same `cltv_delta` as `lnd` then the test succeed.

Now I'm confused. The situation (with defaults which is failing) is the following:

```
c-lightning -- 6 --> lnd
lnd -- 144 --> c-lightning
```
and lnd is enforcing its cltv delta of 144. But isn't my announcement basically meant to convey that I'm ok forwarding payments with a delta of 6? The announcement basically says that in case of a breach I'll need 6 blocks to react to gather any disclosed payment keys from the blockchain. So why should lnd enforce its downstream cltv_delta on its upstream? Or is this me just needing some sleep?

**Comment by sstone** [comment]
@cdecker yes we need to improve this ...
@Roasbeef we don't set the expiry at the current height, we set it at current height + 9 and use the same value for the next cltv expiry since they're is no next hop. I don't understand your comment about sending payments across a link since in this case it's a direct payment (but it's getting late here too :))

**Comment by rustyrussell** [comment]
Olaoluwa Osuntokun <notifications@github.com> writes:
> @sstone that's for the payload itself, meaning the value in the payload should exactly be the value within the HTLC itself. If one sets the CLTV expiry to exactly the current height, then a race condition is introduced. When sending a payment across a link, the routing policy of the target link should be used, not yours. This is due to the fact that you're "transiting" their link essentially. 

Indeed.  It's really a node property but we put it in the channel
update; I can't see any obvious reason for that (in theory, you might
trust some peers more than others, but meh).

Now, it's the side accepting the HTLC which cares about this timeout, so
indeed, we need the reverse's `cltv_expiry_delta`.  Note that this also
implies that you can't use a channel until you have `channel_announce`
from *both* sides.  Worse, you can't use your own channels until 6 deep,
because you need the `channel_announce` from your peer.

I think we *need* to fix this.  First we need to put the
`cltv_expiry_delta` into `open_channel`.

Then there are three options:

1. Just document the limitations.
2. Move `cltv_expiry_delta` from `channel_announce` to `node_announce`.
3. Put the *other* node's cltv_expiry_delta in your `channel_announce`.
   This means you can lie and mess up the channel, but there are other
   ways to do that anyway AFAICT.

Thoughts?
Rusty.

**Comment by pm47** [comment]
> Note that this also implies that you can't use a channel until you have `channel_announce` from *both* sides. Worse, you can't use your own channels until 6 deep, because you need the `channel_announce` from your peer.

If A just opened a channel with B, which already has a channel with C, then for a payment A->C the expiry delta must be the one that B announced for channel B->C, not channel A->B. The spec is pretty clear on that: "It MUST set `cltv_expiry_delta` to the number of blocks it will subtract from an incoming HTLCs `cltv_expiry`." So you can use a channel that is less than 6 conf deep, you only need the *next* channels to be announced. Does that really need fixing?

I think the issue at hand is more basic, and I don't see why we are discussing `cltv_expiry_delta` in the case of a *direct* payment. It doesn't apply here and [BOLT 4#payload-for-the-last-node](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#payload-for-the-last-node) makes it 0 by convention, by stating that `last_per_hop`.`outgoing_cltv_value` must be set to `last_htlc`.`cltv_expiry`, which is what eclair does here. Note that the `final_incorrect_cltv_expiry` error should only be returned if those values where not equal which again is not the case here. FWIW, if the absolute timeout of 9 blocks is deemed to small, then `final_expiry_too_soon` should be used.

Cheers,
Pierre

**Comment by cdecker** [comment]
FWIW I think this is also the elusive issue ElementsProject/lightning#281 :-)

Putting the `cltv_delta` into the `node_announcement` is not a good solution, since me made that message optional on purpose (not every node needs to announce its existence). I kind of like putting the `cltv_delta` into the `open_channel` and then having the `channel_updates` just include the one given by the other endpoint, but I'm unsure if we can actually check that it has been respected.

**Comment by cdecker** [comment]
I'm still not convinced that we really care about the delta of the node receiving the HTLC. Let me give an example:

- Let's say we have a payment `A->B->C->D` at blockheight 100 and deltas are `A=7` `B=3` `C=5` `D=11` (prime to illustrate)
 - That means that channels have deltas `A-7->B`, `B-3->A`, `B-3->C`, `C-5->B` `C-5->D` and `D-11->C`. 
 - The purpose of the delta from `B->C` is that, if `C` had to settle on-chain, then `B` would need some time to be able to extract the `payment key` from the blockchain, turn around and use it to claim the HTLC from `A`.
 - Therefore I think that the `cltv_delta` on the channel `B->C` to be used is the one desired by `B` (namely 3), not the one from `C` (5).

**Comment by pm47** [comment]
> Therefore I think that the cltv_delta on the channel B->C to be used is the one desired by B (namely 3), not the one from C (5).

I agree, my point was that `cltv_delta`=3 has been advertised by `B` in its `channel_update` for channel `B->C` (in your notation `B-3->C`). `A` does *not* need `B`'s `channel_update` for channel `A->B` (in your notation `B-3->A`) in order to send a payment through `B`. So I think the problem described by @rustyrussell doesn't exist.

**Comment by cdecker** [comment]
Well, only the origin of the transfer needs to know about the deltas anyway :wink:

My point is that I as a node announce details of all outgoing edges, and the delta that I advertise is also the delta that I personally care about, no need to have any interaction with the other edge.

**Comment by rustyrussell** [comment]
> I think the issue at hand is more basic, and I don't see why we are discussing cltv_expiry_delta in the case of a direct payment.

Yep, let's break it down:

## The Requirement for a Minimum HTLC Expiry

Consider the direct case: if A wants to pay B, B will have *some requirement* on how close an HTLC expiry can be.  To see why, consider what happens at block N if A pays B with HTLC expiring at N+1:

1.  Both sides get irrevocably committed to the HTLC.
2.  B sends update_fulfill_htlc, marks the payment paid and immediately releases the goods (whatever it is).
3.  A broadcasts its commitment tx onchain, containing the HTLC.
4.  B now has 1 block to spend the HTLC output, otherwise it's in a race with A which can also spend to timeout the HTLC.

Notes:
1.  A can send the tx direct to a miner and B won't see it until it's in a block: it's clear that an HTLC timeout of N+1 is too small. 
2.  Reorganizations mean that we probably want the HTLC buried quite well before it times out, too.
3.  The minimum HTLC timeout is either:  how many blocks until B notices an onchain commitment transaction and can spend the HTLCs and have them "reorg-proof", or how many blocks until B can spend both its commitment tx and the HTLC tx and have them "reorg-proof".

## The Recipient's Requirement for Minimum `cltv_expiry_delta` Is The Same

If B is forwarding the HTLC (not just delivering some goods), the calculation on the HTLC delta  is the same as the calculation above.  Worst case, it will get the HTLC preimage from the outgoing HTLC at block N (just as it's trying to time it out), and now it has until N+`cltv_expiry_delta` to collect the incoming HTLC.  This is exactly the same calculation as above.

## Does The Sender Have A Requirement for a Minimum `cltv_expiry_delta`?  No.

Now let's look at the A->B->C case, where C says `cltv_expiry_delta` is 1: is there a risk to B?  Assume B chose 6 as its `cltv_expiry_delta`, so we have a HTLCs:

A->B: Timeout N+7
B->C: Timeout N+1

C wins the race at block N+1, and reveals the preimage, which B sees at block N+2 (because it only saw C's tx once it was in a block).  B how has 5 blocks, not 6, to collect the incoming HTLC, so we should probably add another 1 to our calculations above.

But there's no fundamental way I can see that a low `cltv_expiry_delta` on outgoing HTLCs is a problem. 

=> The `cltv_expiry_delta` is only important for the *recipient*, not the *sender*, so we currently have it backwards.

## The Worst-Case cltv_expiry_delta Calculation

The worst case is an intermediate node (B), given a worst-case reorganization of depth R:

1. The HTLC times out at block N, B or C drops to chain, B spends HTLC.
2. Bad case: C wins the race and fulfills the HTLC, B only sees transaction when it gets block N+1.
3. Worst case: There's reorganization R deep in which C wins and fulfills.  B only sees transaction at N+R.
4. B needs to fulfill the incoming HTLC, but A or B drops to chain.
5. Bad case: B sees A's commitment transaction in block N+R+1, and has to spend the HTLC output, which takes S blocks to be mined.
6. Worst case: There's another reorganization R deep which A uses to spend the commitment transaction, so B sees A's commitment transaction in block N+R+R, and has to spend the HTLC output, which takes S blocks to be mined.
7. B's HTLC spend needs to be at least R deep before it times out, otherwise another reorg could allow A to timeout the transaction.

The `cltv_expiry_delta` is R*3+S for R>1.  Note that this is a worst-case: The chances of three reorganizations in which the counterparty wins all of them is diminishingly low for R >= 2.  Since we use high fees (and HTLC spends can use almost arbitrary fees) S should be small, though given that block times are irregular and empty blocks still occur, S = 2 should be considered a minimum.

If in doubt, use 9, because that's what ECLAIR does.

(Side note: for a terminal node, the first 3 points don't count, so the minimum CLTV it should accept is R*2+S from the current block).

## `cltv_expiry_delta` is A Weird Name

It's an OK name for the forwarding case (where it's an exact amount), it's a bad name for the terminal case, where it's a minimum delta from the current block: I'd expect every implementation to at least add 1, otherwise a spurious failure occurs every time there's a new block while the HTLC is in transit.

## We Need To Document This

If we agree, I'll try to draft this explanation properly for bolt 2 (I might rename ' Risks With HTLC Timeouts' to 'Setting ctlv_expiry_delta To Avoid HTLC Risks') and bolt 7 (A new section on "Setting HTLC Timeout" which recommends adding at least 1)?

If I'm wrong, please correct me!

**Comment by pm47** [comment]
Hi Rusty,

> The Requirement for a Minimum HTLC Expiry

I agree with everything you said in this section. Please note that in the present case eclair uses a N+9 expiry, which I think you'll agree is reorg-proof? If the other party (lnd in this case) considers it is too small, it should then reply with an `expiry_too_soon` error.

(I am going to comment on your other points, but to me they are unrelated to the specific issue discussed in this ticket.)

> The Recipient's Requirement for Minimum cltv_expiry_delta Is The Same

Agreed.

> Does The Sender Have A Requirement for a Minimum cltv_expiry_delta? No.

Agreed, except that I don't see where "we currently have it backwards."

> cltv_expiry_delta is A Weird Name

I was the one who [proposed](https://github.com/lightningnetwork/lightning-rfc/issues/54#issuecomment-266442367) `cltv_expiry_delta`, and to me its *only* signification is its litteral one: a difference of two *expiries*. I'm glad you think it is an OK name for that ;-).

You seem to be making the point that we should also use `cltv_expiry_delta` for the terminal case? But this would leak a lot of information (at least the last few nodes in the route) and would conflict with the recently added [shadow route recommendations](https://github.com/lightningnetwork/lightning-rfc/pull/208). To be clear I view the current static N+9 last htlc expiry in eclair as a temporary thing.

FWIW, this is not what I had in mind when I said earlier that I didn't believe the problem you were mentioning was real. I was referring to:
> this also implies that you can't use a channel until you have `channel_announce` from *both* sides.

I feel like we are mixing several topics, maybe it would be best to discuss this during the next call?

Cheers,
Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:

> You seem to be making the point that we should also use `cltv_expiry_delta` for the terminal case? But this would leak a lot of information (at least the last few nodes in the route) and would conflict with the recently added [shadow route recommendations](https://github.com/lightningnetwork/lightning-rfc/pull/208/files). To be clear I view the current static N+9 last htlc expiry in eclair as a temporary thing.

Not quite: we should use `cltv_expiry_delta` for the *minimum amount*
allowed for the terminal case.  Because it's about right and we don't
have any other information.

(BTW, I expanded the comment above to include a worst-case analysis.
Answer is 9 :)

> FWIW, this is not what I had in mind when I said earlier that I didn't believe the problem you were mentioning was real. I was referring to:
>> this also implies that you can't use a channel until you have `channel_announce` from *both* sides.

If the *incoming* side dictates the cltv_expiry_delta required for the
channel, and the *outgoing* side dictates the fee required for the
channel, you need to know both?

(Unless we do the "swap cltv_expiry_delta" trick I suggested).

> I feel like we are mixing several topics, maybe it would be best to discuss this during the next call?

I really like being able to drink a coffee and ponder my answers over
email like this.  This topic is *hard* for me!

Thanks,
Rusty.

**Comment by pm47** [comment]
> Not quite: we should use `cltv_expiry_delta` for the *minimum amount* allowed for the terminal case.

Alright, now that makes sense to me. Phew! I can't think of a better name for it though.

> If the *incoming* side dictates the cltv_expiry_delta required for the channel, and the *outgoing* side dictates the fee required for the channel, you need to know both?

If `A` wants to make a payment to `C` through `B`, it needs `cltv_expiry_delta` and `fee_*` required by `B`, right? IIUC, you are saying that `A` should take this values from `B`'s `channel_update` related to channel `A-B`. I'm saying that these values should be taken from `B`'s `channel_update` related to channel `B-C`(*), therefore `A` doesn't need to wait for announcements related to channel `A-B`.

(*) They could very well be the same, expecially `cltv_expiry_delta`, which, I agree with you, is more of a node property. But let's say they are different, because `C` is really suspicious: `B` might want to be extra cautious and will advertise a high `cltv_expiry_delta` in its `channel_update` related to channel `B-C`. This higher `cltv_expiry_delta` is the one that `A` needs to use when paying `C` through `B`, not the regular one that was advertised by `B` for channel `A-B`, right?

> This topic is *hard* for me!

I know that feel!

Cheers,
Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
>> Not quite: we should use `cltv_expiry_delta` for the *minimum amount* allowed for the terminal case.
>
> Alright, now that makes sense to me. Phew! I can't think of a better name for it though.
>
>> If the *incoming* side dictates the cltv_expiry_delta required for the channel, and the *outgoing* side dictates the fee required for the channel, you need to know both?
>
> If `A` wants to make a payment to `C` through `B`, it needs `cltv_expiry_delta` and `fee_*` required by `B`, right? IIUC, you are saying that `A` should take this values from `B`'s `channel_update` related to channel `A-B`. I'm saying that these values should be taken from `B`'s `channel_update` related to channel `B-C`(*), therefore `A` doesn't need to wait for announcements related to channel `A-B`.

A needs the value that B wants, and the value that C wants.  It could
take B's from B-C and C's from C-B, but that doesn't work for the single
hop case.

If A wants to pay B (who has no other channels), how does it know the
minimum CLTV it can use?  Especially if the channel hasn't been
announced (yet).

> (*) They could very well be the same, expecially `cltv_expiry_delta`, which, I agree with you, is more of a node property. But let's say they are different, because `C` is really suspicious: `B` might want to be extra cautious and will advertise a high `cltv_expiry_delta` in its `channel_update` related to channel `B-C`. This higher `cltv_expiry_delta` is the one that `A` needs to use when paying `C` through `B`, not the regular one that was advertised by `B` for channel `A-B`, right?

Yes.  That's why broadcasting each others' values makes sense.  And
having A and B exchange their cltv_expiry_delta values in open_channel /
accept_channel.

This is simplest for routing calculations, too (since it's what everyone
did, though @roasbeef saw the problem and changed his implementation IIUC).

**Comment by cdecker** [comment]
Migrating to BOLT11 style payment requests fixed this :+1:
